### ISSUE TITLE
MSearch & MServer: Crawler

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MLib#45]
- [x] alles was nicht in der Lib sein soll, wird nach M**Server** verschoben ([MServer:feature/MCrawler](https://github.com/mediathekview/MServer/tree/feature/MCrawler))
- [x] M**Search** wird in M**Lib** umbenannt

Original:

Wie ist das genaue Vorgehen bei Änderungen die (nur) den Crawler betreffen und er neu gebaut werden müsste? Vielleicht wären da ein paar Punkte als Vorlage sinnvoll.

Betrifft Branch `zdf-geo-tagging`.

Die Zeilen in [MediathekZDF.java](https://github.com/mediathekview/MSearch/blob/zdf-geo-tagging/src/main/java/mSearch/filmeSuchen/sender/MediathekZdf.java):

````java
} else {
titel = thema; 
````

habe ich mit [bca056d](https://github.com/mediathekview/MSearch/commit/924a6d6553cf5d36acbd145b3b0d85a4e4c9a483#diff-7a0f35906f5103e075ee0f387eeee7dfL141) auch wieder entfernt, die sind bei den Umstellungen wieder "zurückgekommen" (im laufendem Crawler sind sie nicht mehr drin, da habe ich die schon mal entfernt).

**Comment by alex1702** [comment]
Also ich denke alles was nicht mediathekview UND der crawler gemeinsam in MSearch haben sollte vllt auch aus MSearch raus oder das was sie gemeinsam haben in eine weitere Bibliothek (hatte da schon heute mit derreisende77 drüber gesprochen).
Theoretisch müsste die bibliothek jetzt neu gebaut werden und zumindest der crawler bräuchte dann ein update der bibliothek, aber eigentlich brauch der crawler halt an sich nicht neu gebaut werden sondern braucht nur eine neue Versionsnummer. (die die neure bibliothek dann enthält)

**Comment by xaverW** [comment]
das wird aber nicht möglich sein, dass crawler/lib1 und lib2/MediathekView komplett getrennt sind.
vielleicht wäre ein branch "crawler" sinnvoll aus dem dann gelegentlich gemerged wird und ein neuer crawler gebaut wird. Änderungen wird es da immer wieder geben, da wird es nie eine "stabile" version geben.

**Comment by criztovyl** [comment]
Ich würde nicht sagen das es nicht möglich ist, aber womöglich mit Aufwand verbunden ist, der ganz von der Verstrickung von MediathekView <-> MSearch* und MServer <-> MSearch** abhängt.

\* kann ich nicht einschätzen
** eher gering

Ich würde die Crawler-Sachen aus MSearch auch (vorerst) nicht in eine eigene Bibliothek packen, sonder einfach alles das was **nur** ihn betrifft zu MServer umziehen.

**Comment by xaverW** [comment]
wenn es komplett getrennt wird (was natürlich geht) wären aber Klassen (Filmliste, DatenFilm, ,,)  in beiden libs, also doppelt vorhanden.
Wenn aber die Crawler-Sachen umziehen, wären ja die laufenden Anpassungen an die Mediathek abgedeckt.

**Comment by alex1702** [comment]
ja das klingt auch gut, dass man einfach die crawler sachen auch in den crawler umzieht.

**Comment by criztovyl** [comment]
Also soweit trennen nicht ^^
Der Sinn von MSearch ist ja dann erfüllt, wenn nur der Code drin ist, den sowohl MServer alsauch MView brauchen. Ansonsten schleppt ja entweder MView oder MServer unnütz Code (in MSearch) rum, der gar nicht in MView resp. MServer gebraucht wird.

**Comment by xaverW** [comment]
da ist noch einiges drin, dass nur in MView gebraucht wird. Ich hatte da noch vor, die Version "MView -auto" als eigenes jar zu entwickeln und so sicherzustellen, dass nichts "vom GUI" mehr drin ist.
Ist der Grund warum ich einiges nach MSearch ausgelagert habe.
Das kann man aber ruhig zurückstellen.

**Comment by criztovyl** [comment]
Dann sollte MView wieder allen GUI-Code enthalten.

Ich würde folgendes Vorgehen vorschlagen:

0. Neue Lib: M**Lib**
0. Allen nicht-Crawler-Code von M**Search** in M**Lib** kopieren. (Code is also noch in M**Search**)
0. M**View** von M**Search** auf M**Lib** umstellen
0. Allen nicht-Crawler-Code aus M**Search** entfernen
0. Allen Crawler-Code aus M**Server** nach M**Search** .
0. M**Server** aufgeben & M**Search** wird Crawler.

Um Verwirrung zu vermeiden sollte M**Search** dann möglw. noch einen anderen Namen bekommen, bspw M**Crawler**.

Außerdem dann auch noch allen GUI-Code aus M**Lib** nach M**View** umziehen, aber betrifft nicht diesen Issue.

Dann haben wir
M**Lib** = Bibliothek
M**Crawler** = Crawler
M**View** = nunja... MediathekView ... :D

**Comment by xaverW** [comment]
> MView = nunja... MediathekView ... :D

ich hätte da kein Problem damit

**Comment by criztovyl** [comment]
Dann hau' ich mal in die Tasten. (Huh, vergessen Comment zudrücken :D gn8)

**Comment by xaverW** [comment]
https://github.com/mediathekview/MSearch/issues/53
ist wieder ein Beispiel, warum es leicht möglich sein muss, einen neuen Crawler zu bauen und in Betrieb zu nehmen:
Das ORF hat einen variablen Teil in der URL der sich im laufe des Tages ändert, der muss beim Vergleich auf "neue Filme" ausgeblendet werden und der variable Teil hat sich geändert. Da werden jetzt Filme mehrfach im Laufe eines Tages hinzukommen.

**Comment by alex1702** [comment]
Ja da haste recht. Was sagst du zu #52 ? Wenn ich das entfernen könnte würde ich eine neue Version erstellen für beides.

**Comment by Nicklas2751** [comment]
@criztovyl Hast du bereits code umgezogen? Wenn ja kannst du den bitte Zeitnah einchecken? Dann kann ich hier mit angreifen. Bzw. wenn es dafür noch nicht zu spät ist, würde es nicht schneller gehen grundsätzlich erstmal MSearch zu kopieren und dann alles raus zu werfen was hier nicht reingehört?

**Comment by xaverW** [comment]
> Bzw. wenn es dafür noch nicht zu spät ist, würde es nicht schneller gehen grundsätzlich erstmal MSearch zu kopieren und dann alles raus zu werfen was hier nicht reingehört?

genau so muss es gemacht werden, vorher auch noch MView darauf umbiegen, dass man auch sieht, was gebraucht wird

**Comment by alex1702** [comment]
So war es geplant ja. Da oben nix weiter abgehakt ist, kannst du das denk ich einfach aufgreifen und umsetzen Nicklas.

**Comment by criztovyl** [comment]
Huh, der Code ist sehr miteinander verschränkt, konnte bisher nur `MSearch.java` und `Main.java` entfernen.

War als letztes dabei `ListeFilme.java` von `MediathekKiKa` zu lösen*, aber dann sind die Filme vom KiKa wieder doppelt drin. Ich habe das noch versucht zu beheben und bin dazu jetzt noch nicht gekomm'.
Ich committe den Status Quo heut' abend mal vernünftig & push das hoch.
Vorerst würde ich auf ner Branch in MSearch bleiben und die dann nach Abschluss mit `filter-branch` zu nem eigenen Repo zu machen.

* Habe eine Subklasse `ListeFilmeSuchen` angelegt, in die ich die Crawler-spezifischen Sachen pack'.

**Comment by derreisende77** [comment]
Ich bitte darum bei Änderungen an ListeFilme extrem vorsichtig zu sein. 
Diese wird sehr häufig in MV verwendet und könnte dort funktionierende 
Logik zerstören.


Am 22. November 2016 12:15:03 schrieb Christoph Schulz 
<notifications@github.com>:

**Comment by xaverW** [comment]
> War als letztes dabei ListeFilme.java von MediathekKiKa zu lösen*
BITTE da keine Experimente!! So wie ich es verstanden habe, soll doch die lib auch im Crawler importiert werden?? Also muss die "ListeFilme" nicht aus MediathekKiKa entfernt werden (KikA muss aus der Lib).

Ich würde dringend empfehlen, erst mal eine 1:1 Kopie von MSearch zu nehmen, MView darauf umbiegen und dann erst anfangen die Sachen die dann dort (in der neuen Lib) nicht mehr gebraucht werden (Gui, MediathekReader, ..) zu entfernen.

**Comment by alex1702** [comment]
Da bin ich auch für.

**Comment by criztovyl** [comment]
@xaverw Ohne dir jetzt widersprechen zu wollen, aber natürlich wird hier erstma' experimentiert werden, v.a. was geht & was nicht. Es ist ja nicht so, das ich jetzt vorhab' die Änderungen direkt, ungetestet, auszurollen :D
Und das mit MediathekKiKa & ListeFilme hast du falschrum verstanden: Es geht nicht darum in MediathekKiKa keine ListeFilme mehr zu nutzen, sondern darum, keine MediathekKiKa mehr in ListeFilme zu nutzen. (ListeFilme#updateListe war's wenn ich mich richtig erinnere).

Und das mit der 1:1 Kopie geschieht ja mit der Branch so. Das entflechten der Klassen gehört für mich aber noch zu MSearch und bevor das nicht richtig abgeschlossen ist, würde ich auch noch nicht mit MLib anfangen. (Ich passe die ToDo Liste oben dementsprechend an).

**Comment by criztovyl** [comment]
Ich werde es heut' leider weder schaffen zu commiten noch zu pushen. Ich kümmer' mich da aber morgen drum.

**Comment by criztovyl** [comment]
@all Da ich mir jetzt nicht sicher bin ob's alle mitbekomm' haben, erwäh'n ich's sicherheitshalber nochmal: Ich habe ganz oben im Issue-Text die ToDo-Liste aufgeschrieben.
Damit es nicht zu Verwirrung kommt.

**Comment by xaverW** [comment]
Wenn du in MSearch einen branch dafür angelegt hast, wäre es da nicht auch besser, in MServer auch einen anzulegen und dort das entfernte gleich einzufügen und so auch den neuen Crawler zu bauen. Dann könnte man, wenns läuft, mergen und die 2 Projekte einfach nur mit den Wunschnamen versehen. An MView müsste dann gar nichts geändert werden und ein neues Projekt muss auch nicht eingerichtet werden.

**Comment by alex1702** [comment]
Wäre auch eine idee ja.

**Comment by criztovyl** [comment]
Noch habe ich keine Branch angelegt.
Um der Nachvollziehbarkeit* Willen würde ich mit dem Löschen/Verschieben noch warten bis die Trennung vollständig abgeschlossen ist.

Das wirkliche Trennen später sollte auch nicht mit wirklichem löschen sondern via `git filter-branch` geschehen, wg. der o.g. Nachvollziehbarkeit*.

\* Nachvollziehbarkeit in dem Sinne, weiterhin die Historie der Datei nachverfolgen zu können. Würden wir die Datei einfach nur mit nem 100% - und nem 100% + Commit verschieben würde ja die Historie verloren gehen.

**Comment by criztovyl** [comment]
Lasst uns wirklich nicht parallel über das verschieben reden, erstmal die Klassen entflechten, ich würde bevorzugen beides getrennt voneinander zu betrachten.

**Comment by criztovyl** [comment]
> [...] konnte bisher nur MSearch.java und Main.java entfernen.

Diese Aussage ist so nicht ganz richtig und hat für Verwirrung gesorgt.
Ich meinte damit, das ich es geschafft habe MV mit einer MSearch JAR ohne diese beiden Klassen laufen zu lassen, wobei eine Anpassung in `mSearch.tool.Functions` nötig war ([Funtions.java Z110](https://github.com/mediathekview/MSearch/blob/674b90703df5bc5274f184de45aeff0f33f5424b/src/main/java/mSearch/tool/Functions.java#L110)).

**Comment by criztovyl** [comment]
Okay, meine bisherige Arbeit ist jetzt oben. Ich habe sie in [feature/#45-crawler-code](https://github.com/mediathekview/MSearch/tree/feature/%2345-crawler-code) gepusht.

Wenn wir auf dieser Branch zusammenarbeiten wollen, schlage ich vor diese wie eine `develop` Branch zu behandeln, also davon Featurebranches zu erstellen.
Wenn wir das so machen, sollten wir den `feature/´-Teil vor dem Branchnamen wegzulassen, sie also nur crawler-coder o.ä. nennen.

**Comment by xaverW** [comment]
ganz klar ist mir das nicht wie der (spätere) Ablauf ist, schaus mir aber mal an (versteh auch nicht ganz, was der Vorteil von dem Aufwand ist?)

**Comment by criztovyl** [comment]
Hm, wo liegt für dich hier der Mehraufwand?

**Comment by xaverW** [comment]
wenn ich früher das Programm umgebaut habe, wurden die Klassen die in einem entfernt wurden tatsächlich verschoben, also dorthin gesteckt, wo sie sollten, Netbeans hat das Refactoring perfekt beherrscht. Aber wie gesagt, ich schau mir das gerne mal an, wie du das vorhast, lerne gerne dazu. Durch das "live" hat man auch sofort gesehen, obs "klappt"

**Comment by criztovyl** [comment]
@xaverW Das Entflechten was ich gerade mache findet auf Methodenebene statt, nicht auf Klassenebene, wennauch da sicher trotzdem das NetBeans Refactoting greift ^^ (Wobei ich selbst ohne IDE arbeite.)
Und nen bisschen "live" seh' ich das auch, allerspätestens Gradle zickt rum wenn da was nicht stimmt. (Ich arbeite da mit `gradle compileJava -t`, baut dann bei ner Änderung sofort neu.)

Ansonsten werde ich jetzt eine Branch anlegen, auf der wir dann gemeinsam arbeiten können.
Ich würde auf dieser Branch dann auch git-flowig arbeiten, also nicht direkt auf der Branch sondern mit "Feature"-Branches. In dem Fall würde ich's dann aber als "Refactor"-Branch bezeichen und auch das Präfix dementsprechend von `feature` auf `refactor` ändern. (Über das Präfix können wir gerne noch diskutieren.)
Und um die Verifikation/Kontrolle/Bestätigung etwas zu vereinfach würde ich vorschlagen entweder mit PRs zu arbeiten und/oder hier die Merge-Commits zu verlinken.

**Comment by criztovyl** [comment]
ich hab meine Änderungen an ListeFilme mal als PR gemacht ^^

**Comment by criztovyl** [comment]
Ich würde dann als nächstes `DatenFilm` angehen oder arbeitet da schon jmd dran? :)

**Comment by Nicklas2751** [comment]
Von mir aus passt das.

**Comment by xaverW** [comment]
> Das Entflechten was ich gerade mache findet auf Methodenebene statt, nicht auf Klassenebene, wennauch da sicher trotzdem das NetBeans Refactoting greift 

und mit NetBeans ist die ganz große Arbeitserleichterung, dass es sich um die ganzen notwendigen "Umbenennungen" usw. selbständig kümmert

**Comment by Nicklas2751** [comment]
Wie eclipse und IntelliJ auch ;)

**Comment by criztovyl** [comment]
Dem Workflow widersprech' ich ja gar nicht ^^ (Wennauch ich ihn so nicht nutze).

Mir ging's/geht's nur darum, das die Klasse in die die Methode kommt, noch in MSearch angelegt wird, nicht in MServer, MLib oder MV. :)

**Comment by xaverW** [comment]
ListeFilmeSuchen.updateListe

das wird 2x aufgerufen (das erste ist zu früh):
listeEinsortieren.forEach(this::addInit);

und die Liste wird durch das Aufteilen in 2 Methoden auch 2x abgearbeitet. In die ganzen Methoden ist viel Zeit geflossen, um sie möglichst effizient zu machen und so wird das alles wieder verspielt. Kann man nicht einfach Konstanten für die Sendernamen anlegen damit die allgemein genutzt werden können?
MediathekKika.SENDERNAME ist ja nur eine statische Konstante?

**Comment by xaverW** [comment]
ich würde mal wieder Vorschlag machen: am wichtigsten ist es doch, die Sender umzuziehen, das ist es doch, das am häufigsten geändert wird.
Da wir da eh nicht alle gleichzeitig daran arbeiten können: ich würde im Server/Crawler je einen branch anlegen: 'move' und mal die Sender umziehen. So dass das wesentliche schon mal im Server ist. Dann kann man die anderen Sachen Stück für Stück (wo überhaupt notwendig) nachziehen.

Wir sollen hier doch keine Programmierparadigmen Lehrbuchreif umsetzen sondern es soll ein gutes und wartbares Produkt herauskommen?

(weiß dass meine Vorschläge immer abgelehnt werden, wäre aber doch zumindest einen Blick wert?)

**Comment by criztovyl** [comment]
Ich würde nix mehr zu MServer umziehen, ich wollte MServer als Crawler aufgeben und MSearch zum Crawler machen, nen Umzug wär' unnötige „Müh'”.

Sobald `DatenFilm` keine `MediathekOrf` mehr referenziert, kann die Klasse & `ListeFilme` schon mal nach MLib und womit zwei Kernelemente umgezogen wären.

Deine Vorschläge sind ihren Blick wert.
Sie werden ja nicht abgeleht weil wir dich nicht mögen oder so. Bspw. ist mein Workflow & „Anspruch” an den Code einfach  nen anderer, das ist der Grund warum ich meist dagegen bin, das geht nicht gegen dich persönlich :)
Menschen haben unterschiedliche Ansichten, wie was gehört. Du hast dieses Produkt geschaffen, oder wenigstens lange weitergeführt, ich kenne die Geschichte hier nicht genau. Es ist dein Produkt, dein Baby. Aber du hast dich entschlossen es und, der Community, zu überlassen. Ich, wir, schätzen deine Leistungen. Danke, Xaver. Aber jetzt sind wir dran. Du hast uns die Verantwortung übergeben. Ich, wir, sind anders. Denken anders. Möchten Dinge anders machen. Und wir sind viele gegen einen, daher kommt dein Eindruck, wir lehnen deine Vorschläge immer ab, ob's nu' so ist oder nicht. Das geht nicht gegen dich, das neue Team hat einfach nur eine andere Dynamik.

Und ich glaube die Geschwindigkeit hat in diesem Fall auch keinen großen Einfluss auf das Produkt MV. 
Das hier ist nix derart kritisches, das es zur Not nicht auch bis zum übernächsten Release (14) warten könnte, die letzten zwölf Versionen ging's ja auch :)

**Comment by lookshe** [comment]
> Ich würde nix mehr zu MServer umziehen, ich wollte MServer als Crawler aufgeben und MSearch zum Crawler machen, nen Umzug wär' unnötige „Müh'”.

Wäre es nicht sinnvoller bestimmte Dinge getrennt zu halten? Meines Wissens ist MSearch für die Suche selbst zuständig und MServer steuert die Suche und die Such-Threads. Hier ist also eine schöne und sinnvolle Trennung gemacht worden. Warum sollte man das jetzt aufgeben und vermischen?

**Comment by alex1702** [comment]
Ich stelle diese Entwicklung erstmal auf Pause, ich komme hier grad nicht mehr hinterher und es sollte erstmal ein Plan gemacht werden. Es scheint doch mehr in einander verworben zu sein.

**Comment by alex1702** [comment]
> Menschen haben unterschiedliche Ansichten, wie was gehört. Du hast dieses Produkt geschaffen, oder wenigstens lange weitergeführt, ich kenne die Geschichte hier nicht genau. Es ist dein Produkt, dein Baby. Aber du hast dich entschlossen es und, der Community, zu überlassen. Ich, wir, schätzen deine Leistungen. Danke, Xaver. Aber jetzt sind wir dran. Du hast uns die Verantwortung übergeben. Ich, wir, sind anders. Denken anders. Möchten Dinge anders machen. Und wir sind viele gegen einen, daher kommt dein Eindruck, wir lehnen deine Vorschläge immer ab, ob's nu' so ist oder nicht. Das geht nicht gegen dich, das neue Team hat einfach nur eine andere Dynamik.

Also deine Ausdrucksweise gefällt mir hier nicht.
1. Xaver gehört zum Team und der Community.

> Aber jetzt sind wir dran
2. Sollche Aussagen gehören hier nicht hin.

**Comment by criztovyl** [comment]
Hm, vllt habe ich mich etwas... nunja. ausgedrückt.
Ich wollte nur sagen, das hier Xavers Vorschläge nicht generell abgeschmettert werden weil wir ihn jetzt doof finden weil er mit der Haupt"beruflichen" Entwicklung aufhört. 
Sry.

**Comment by criztovyl** [comment]
@lookshe Ich widerspreche nicht, dass das getrennt gehört, für mich reicht es in dem Fall aber das innerhalb eines Projektes "Crawler" getrennt wird, das dort der Code an sich nicht vermischt wird.
Das wäre für mich MSearch.

@alex1702 Sowohl in der Issue-Beschreibung als auch [hier](https://github.com/mediathekview/MSearch/issues/45#issuecomment-260204991) habe ich einen Plan beschrieben.

**Comment by criztovyl** [comment]
@xaverW AW: https://github.com/mediathekview/MSearch/issues/45#issuecomment-263008372
Herrje, diesen Kommentar habe ich vollkommen übersehen. Ich denk nochmal drüber nach.

**Comment by xaverW** [comment]
und ich habe auch schon mal geschrieben, dass man die Aufteilung erst mal in Server / MSearch machen kann und die Projekte dann in die gewünschten Namen umbenennen kann. Es käme dann das gleiche raus wie oben vorgegeben, alles nur einfacher und **sicherer**

**Comment by criztovyl** [comment]
Bei dem mit ListeFilme#updateListe meinst du [hier](https://github.com/criztovyl/MSearch/blob/d93de5cad7e0c34dad64a75c0b4ce7cef032defc/src/main/java/mSearch/daten/ListeFilme.java#L100) und [hier](https://github.com/criztovyl/MSearch/blob/d93de5cad7e0c34dad64a75c0b4ce7cef032defc/src/main/java/mSearch/daten/ListeFilmeSuchen.java#L66)?

**Comment by xaverW** [comment]
ja

**Comment by criztovyl** [comment]
Und mit der Trennung (M?)Server/MSearch meinst du das bspw. alles in mSearch.filmeSuchen.sender nach MServer geht, soweit das möglich ist?

**Comment by xaverW** [comment]
ja

**Comment by criztovyl** [comment]
Lt. Plan wird doch MServer aber in MSearch integriert, also wäre der Umzug doch sinnlos?

Ich hab den Plan nicht aus Langeweile zum Spaß an der Freude gemacht, da wollt' ich mich schon dran halten. (Geht an alle, nicht an dich spezifisch.)

**Comment by xaverW** [comment]
ich versteh dein Problem nicht?
alles was nicht in der lib sein soll, wird nach server verschoben,
msearch wird in lib umbenannt (und enthält dann nur noch das was eben in der lib sein soll)
server wird in msearch umbenannt

wo ist jetzt der Unterschied zu oben?

**Comment by alex1702** [comment]
Ich finde so wie xaver es schreibt sollten wir es machen.

**Comment by criztovyl** [comment]
- oben wird der Nicht-Crawler-Code verschoben, wobei du den Crawler-Code verschieben möchtest.
- oben wird nix umbenannt.

Da liegt der kleine, aber feine Unterschied.

Ich habe da jetzt kein Problem mit, außer das ich meinen Plan besser find' :D

**Comment by alex1702** [comment]
Ja aber ich denke andersrum ist es besser. somit wird auch kein neues Repo erstellt wo man alles neu einstellen muss.

**Comment by criztovyl** [comment]
In der Zwischenzeit hab' ich mir was für ListeFime#updateListe ausgedacht: https://github.com/mediathekview/MSearch/pull/74

**Comment by criztovyl** [comment]
Einfach nochmal für's Feedback:

**Comment by criztovyl** [comment]
Mein Weg (:+1:)

**Comment by criztovyl** [comment]
Xavers Weg (:+1:)

**Comment by xaverW** [comment]
eigentlich gings doch nur darum, ob es sinnvoll ist, die ganzen Methoden zu zerrupfen nur um die Sendernamen nicht  als Konstante in der Lib anzulegen??
MediathekKika.SENDERNAME wir zB. auch in MView verwendet, mit deinem Vorschlag: ListeFilme#updateListeLambda alleine ist es also nicht getan und vielleicht werden die nochmal für was gebraucht.
In welcher Reihenfolge dann was aussortiert wird, sollte sich doch dann einfach nach dem geringsten Arbeitsaufwand richten. Das ist mir im Endeffekt egal aber ich würde dringend davor abraten, einfach mal die ganzen Methoden zu ändern. Da wurde viel Zeit rein gesteckt (und auch viel gemessen) um das möglichst effizient zu machen.

**Comment by criztovyl** [comment]
Ich habe mich da wohl etwas übernommen, ich ziehe mich hier lieber zurück.

**Comment by xaverW** [comment]
ich habe mal einen Anfang gemacht: feature/MCrawler
(branch in MView: da hat sich aber fast nix geändert, MSearch, MServer)

da sind die Sender und die Gui von MSearch nach MServer gewechselt (und alles was dazu notwendig war).
MView läuft wie vorher
die Gui für den Crawler startet jetzt so (MServer zip entpacken): ./bin/MServer -gui
und der "normale" Server wie bisher: ./bin/MServer

jetzt muss dann noch etwas weiter in die Tiefe gegangen werden um noch alles was nicht in die lib muss, raus zu nehmen. (GetFileSize ist jetzt zB. doppelt drin, ..)

**Comment by alex1702** [comment]
Der Crawler hat ne gui?

**Comment by xaverW** [comment]
ja, schon immer.


Am Sun, 27 Nov 2016 16:31:54 -0800
schrieb Alexander <notifications@github.com>:

> Der Crawler hat ne gui?
>

**Comment by alex1702** [comment]
Oh ok. Ist die nötig?

**Comment by derreisende77** [comment]
Ja


Am 28. November 2016 08:52:54 schrieb Alexander <notifications@github.com>:

**Comment by xaverW** [comment]
habe einen merge beantragt ,)
habe die Sachen zum Erstellen der Filmliste nach MServer verschoben. Bei mir läuft mein Crawler aktuell bereits mit dem neuen Code, es mussten nur die Libs (wie bisher) ausgetauscht werden.

was mir noch aufgefallen ist: Das Erstellen der Logs wäre noch ein Punkt, würde da aber ein eigenen Feature dafür aufmachen, müsste man auch erst mal schauen, was das sinnvoll ist.

Was die Umbenennung angeht, das sollten die gradle-Spezialisten machen. Wenn ich das Projekt in Netbeans einfach umbenenne, wirds da wahrscheinlich Probleme geben??

Mir ist auch noch ein Punkt eingefallen wegen der Namen: den jetztigen MServer dann in MSearch umzubenennen könnte vielleicht zu Irritationen führen, vielleicht wäre da MCrawler oder so besser. So dass klar ist, dass es nicht das gleiche ist (nur so eine Idee).

**Comment by alex1702** [comment]
Voll nice :)
Ja Logs ist noch nicht so geil. Nur falls ich das übersehen hab, man kann aktuell noch nicht einstellen wo die logs abgespeichert werden sollen oder?
auch das logrotate im sinne von jeder tag bekommt sein eigenes logfile würde ich gerne überarbeiten.
Ich möchte gerne nach /var/log loggen und den logrotate dienst drüber laufen lassen. Ich weiß nicht ob ihr das feature unbedingt braucht zum ausprobieren. ich kann auf diese funktion gut verzichten.
Ja denke MCrawler könnte verwirrungen vorbeugen.

**Comment by xaverW** [comment]
die Logdateien landen im "Basisverzeichnis/log", ist das Konfig vom
Verver und das kann man nicht ändern.

Würde dafür aber ein eigenes feature machen, nicht dass der Source zu
weit auseinander läuft. So läuft das Programm komplett im Userspace,
wenn es nach /var/log schreiben soll, muss es höhere Rechte haben, weiß
nicht ob das gut ist??





Am Mon, 28 Nov 2016 10:32:59 -0800
schrieb Alexander <notifications@github.com>:

> Voll nice :)
> Ja Logs ist noch nicht so geil. Nur falls ich das übersehen hab, man
> kann aktuell noch nicht einstellen wo die logs abgespeichert werden
> sollen oder? auch das logrotate im sinne von jeder tag bekommt sein
> eigenes logfile würde ich gerne überarbeiten. Ich möchte gerne
> nach /var/log loggen und den logrotate dienst drüber laufen lassen.
> Ich weiß nicht ob ihr das feature unbedingt braucht zum ausprobieren.
> ich kann auf diese funktion gut verzichten. Ja denke MCrawler könnte
> verwirrungen vorbeugen. 
>

**Comment by alex1702** [comment]
Wenn man den log Ordner anpasst und die Rechte auf den ausführen User gibt, dass geht es auch so. Man muss halt nur es vorher machen. Ginge auch eher darum, dass man ein logpath angeben kann und wenn keiner gesetzt ist kann er ja trotzdem um basisverzeichnis unter log loggen.

**Comment by iamhenning** [comment]
Hab die Diskussion nur passiv ab und an verfolgt und bin jetzt nach einigen Änderungen am Repo etwas verwirrt... 
da fehlt doch jetzt einiges, oder? Beispiel: Egal wo ich reinschau, die Crawler-Logic der Sender findet sich scheinbar nirgends mehr. Ich mag mich irren, aber früher war das doch unter https://github.com/mediathekview/MSearch/tree/master/src/main/java/mSearch/filmeSuchen, jetzt ist es weder in MLib, MServer, MSearch noch sonstwo. Oder ist das in irgendeinen undurchsichtigen Branch abgetaucht?
Verwirrte Grüße.

**Comment by xaverW** [comment]
https://github.com/mediathekview/MServer/tree/master/src/main/java/mServer/crawler

ist nichts verloren.
(master)

**Comment by Nicklas2751** [comment]
Wie ist denn hier der aktuelle Stand?

**Comment by xaverW** [comment]
> Was die Umbenennung angeht, das sollten die gradle-Spezialisten machen. Wenn ich das Projekt in Netbeans einfach umbenenne, wirds da wahrscheinlich Probleme geben??

ansonsten wäre das vorerst mal erledigt. Kleiner Sachen werden sich schon noch finden, die man umziehen kann/sollte aber das muss ja dann nicht mehr hier rein.

(wie schon angemerkt: log, sollte aber ein eigener Punkt werden)

**Comment by Nicklas2751** [comment]
oki thx
