### ISSUE TITLE
ZDF Url manuell hochsetzen

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MLib#67]
will hier mal zusammenfassen welche URLs sich hoch setzten lassen. Die Beispiele habe ich gefunden:

https://nrodlzdf-a.akamaihd.net/none/zdf/15/02/150202_alfredkinsey_inf/12/150202_alfredkinsey_inf_1456k_p13v11.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/15/02/150202_alfredkinsey_inf/12/150202_alfredkinsey_inf_2256k_p14v11.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/15/02/150202_alfredkinsey_inf/12/150202_alfredkinsey_inf_2328k_p35v11.mp4

https://nrodlzdf-a.akamaihd.net/none/zdf/16/06/160619_schoeneneuewelt_zei/2/160619_schoeneneuewelt_zei_1456k_p13v12.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/06/160619_schoeneneuewelt_zei/2/160619_schoeneneuewelt_zei_2256k_p14v12.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/06/160619_schoeneneuewelt_zei/2/160619_schoeneneuewelt_zei_2328k_p35v12.mp4
--> und nach HD
https://nrodlzdf-a.akamaihd.net/none/zdf/16/06/160619_schoeneneuewelt_zei/2/160619_schoeneneuewelt_zei_3256k_p15v12.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/06/160619_schoeneneuewelt_zei/2/160619_schoeneneuewelt_zei_3328k_p36v12.mp4

https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_asp/1/161118_sendung_asp_1496k_p13v13.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_asp/1/161118_sendung_asp_2296k_p14v13.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_asp/1/161118_sendung_asp_2328k_p35v13.mp4
--> und nach HD
https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_asp/1/161118_sendung_asp_3296k_p15v13.mp4
https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_asp/1/161118_sendung_asp_3328k_p36v13.mp4

so werde ich das mal im branch dazu einbauen
weitere einfach anfügen

ergibt die Ersetzungen:
```

        // manuell die Auflösung hochsetzen

        //große URL verbessern
        changeUrl("2256k_p14v11.mp4", "2328k_p35v11.mp4", film, urlSeite, mSFilmeSuchen);
        changeUrl("2256k_p14v12.mp4", "2328k_p35v12.mp4", film, urlSeite, mSFilmeSuchen);
        changeUrl("2296k_p14v13.mp4", "2328k_p35v13.mp4", film, urlSeite, mSFilmeSuchen);

        //klein nach groß
        changeUrl("1456k_p13v11.mp4", "2328k_p35v11.mp4", film, urlSeite, mSFilmeSuchen);
        changeUrl("1456k_p13v11.mp4", "2256k_p14v11.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so

        changeUrl("1456k_p13v12.mp4", "2328k_p35v12.mp4", film, urlSeite, mSFilmeSuchen);
        changeUrl("1456k_p13v12.mp4", "2256k_p14v12.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so

        changeUrl("1496k_p13v13.mp4", "2328k_p35v13.mp4", film, urlSeite, mSFilmeSuchen);
        changeUrl("1496k_p13v13.mp4", "2296k_p14v13.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so

        // manuell die Auflösung für HD setzen, 2 Versuche
        updateHd("1456k_p13v12.mp4", "3328k_p36v12.mp4", film, urlSeite);
        updateHd("2256k_p14v12.mp4", "3328k_p36v12.mp4", film, urlSeite);
        updateHd("2328k_p35v12.mp4", "3328k_p36v12.mp4", film, urlSeite);

        updateHd("1456k_p13v12.mp4", "3256k_p15v12.mp4", film, urlSeite);
        updateHd("2256k_p14v12.mp4", "3256k_p15v12.mp4", film, urlSeite);
        updateHd("2328k_p35v12.mp4", "3256k_p15v12.mp4", film, urlSeite);

        updateHd("1496k_p13v13.mp4", "3296k_p15v13.mp4", film, urlSeite);
        updateHd("2296k_p14v13.mp4", "3296k_p15v13.mp4", film, urlSeite);
        updateHd("2328k_p35v13.mp4", "3296k_p15v13.mp4", film, urlSeite);

        updateHd("1496k_p13v13.mp4", "3328k_p36v13.mp4", film, urlSeite);
        updateHd("2296k_p14v13.mp4", "3328k_p36v13.mp4", film, urlSeite);
        updateHd("2328k_p35v13.mp4", "3328k_p36v13.mp4", film, urlSeite);

```

**Comment by xaverW** [comment]
ist so im source drin, evtl. kommt noch was??

**Comment by zxsd** [comment]
Vom MV-Forum ... [Betreff: ZDF-Filme: keine flüssige Wiedergabe via QuickTime (macOS)](http://zdfmediathk.sourceforge.net:80/forum/viewtopic.php?p=13446#p13446)

> MP4 Dateien aus der ZDF Mediathek mit höheren Auflösungen - mit MediathekView heruntergeladen - werden in allen Apple-eigenen Programmen (Quicktime, Quicktime 7, FinalCut etc.) nicht richtig abgespielt. **VLC oder Premiere machen _keine_ Probleme.** 

Es zittern/ruckeln:
>2328k_p35v13.mp4
>3328k_p36v13.mp4

Während OK abspielen:
>2296k_p14v13.mp4
>3296k_p15v13.mp4
> 
>Auf den ersten Blick sind bei der Kodierung jeweils unterschiedliche [GOP](https://helpx.adobe.com/de/media-encoder/using/export-settings-reference.html) settings verwendet worden.

Das Verhalten wurde bestätigt:

> Weitere Analyse: Die "stotternden" Videos verwenden 24 konsekutive B-Frames zwischen den Referenzframes, also zwischen dem I-Frame und dem nächsten P-Frame. Meines Wissens ist eine solche lange Folge von B-Frames absolut unüblich, üblich sind 3–5 konsekutive B-Frames. Die nicht stotternden Videos verwenden gar keine B-Frames, sondern nur I- und P-Frames (wobei B-Frames vom QTKit sehr wohl verstanden werden). Das kann man überprüfen, indem man die Videos mit dem Video-Schnittprogramm Avidemux öffnet, welches interessanterweise beim Öffnen der problematischen Videos auch die Meldung "Some timing information are incorrect" wiedergibt.

**Comment by Nicklas2751** [comment]
Hmm da es scheinbar bei den nicht vom ZDF gelisteten Auflösungen u.U Probleme gibt stellt sich mir die Frage ob das manuelle hochsetzen so sinnvoll ist und ob das ZDF die nicht aus einem guten Grund nicht listet z.B. eben weil die nicht dafür gedacht sind ausgeliefert zu werden. Bzw. je nach dem wie deren Backend aussieht müssen das ja keine Datein sein die bereits existieren sondern deren Backend software erzeugt die auf Anfrage und ist bei denen die Probleme machen noch nicht ganz ausgereift.

Kurz gesagt, ist das wirklich sinnvoll hier manuell hoch zu setzen und nich das an zu beiten was das ZDF von sich aus hergibt/listet?

**Comment by zxsd** [comment]
https://github.com/mediathekview/MServer/issues/32#issuecomment-265644431
