### ISSUE TITLE
Bereitsgeladene Filme werden erneut geladen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MLib#69]
## System:

- Windws 10 x64
- Oracle JDK 8u111
- MediathekView Version 12 (13.840)

## Vorbedingungen

Ich habe gestern Nachmittag das letzte mal meine Filmliste geladen und alle neuen Filme aus den Abos wurden heruntergeladen.

## Erwartetes Verhalten

Filmliste wird aktualisiert und neue Filme werden heruntergeladen.

## Vorgefundenes Verhalten

Filmliste wurde aktualisiert und einige bereits heruntergeladene und gesehne Filme wurden erneut in die Downloadliste hinzugefügt. Einen Screenshot habe ich angehängt.

Filmliste von: 24.11.16, 16:43 Uhr (siehe Anhang)

[filmliste.zip](https://github.com/mediathekview/MSearch/files/611735/filmliste.zip)
![mediathekview-24112016-1653](https://cloud.githubusercontent.com/assets/4107593/20604443/9f8d106c-b266-11e6-97e8-cae1bbbbdce3.png)

**Comment by xaverW** [comment]
und wo ist der Bug? MView, MSearch? Haben die tatsächlich die gleiche URL? Schau doch mal in die downloadAbos.txt

**Comment by Nicklas2751** [comment]
Ein Auschnitt aus der Datei für eine Datei:
[downloadAbos_Ausschnitt.txt](https://github.com/mediathekview/MSearch/files/612175/downloadAbos_Ausschnitt.txt)

Das sieht so aus als wurde durch die crwaler änderungen im laufe der Zeit verschieden gute Versionen gefunden. Eingestellt ist das Abo auf HD.

Und hier noch meine, von den Abos her, reduzierte mediathekview.xml:
[mediathek_Ausschnitt.xml.txt](https://github.com/mediathekview/MSearch/files/612178/mediathek_Ausschnitt.xml.txt)


Ich denke also es ist doch kein MSearch/Crwaler bug sondern eher nen MView fehler. Oder?

**Comment by zxsd** [comment]
Hier ist ein Testfall, daß vielleicht hilft.  (Hint. Seit der Umstellung wurde, und wird immer noch, das ZDF-Crawler-Verfahren verbessert an der ZDF-Webpräsenz angepaßt.)

Die Zeile-Nummer ist dabei, um zu unterstreichen, wie diese Einträge eigentlich in der jeweiligen Dateie aufgelistet sind. 
 
```
downloadAbos.txt
------------------
Zeile Nr. - 71674
24.11.2016 |#| Serien                    |#| Bella Block - Falsche Liebe               |###|  https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161120_falsche_liebe_bel/1/161120_falsche_liebe_bel_2328k_p35v13.mp4
Zeile Nr. - 36559
27.05.2015 |#| Bella Block               |#| Falsche Liebe                             |###|  http://nrodl.zdf.de/none/zdf/15/05/150525_falsche_liebe_ps_bel_2256k_p14v11.mp4
Zeile Nr. - 20516
01.07.2014 |#| ZDFneo                    |#| Bella Block - Falsche Liebe     |###|  http://nrodl.zdf.de/none/zdf/14/06/140617_bella_block_liebe_neo_2256k_p14v11.mp4
Zeile Nr. - 6216
10.07.2013 |#| Ganze Filme im ZDF        |#| Bella Block: "Falsche Liebe"    |###|  http://nrodl.zdf.de/none/zdf/13/03/130321_bella_block_liebe_neo_1596k_p13v9.mp4
Zeile Nr. - 2453
29.03.2013 |#| Ganze Filme im ZDF        |#| Bella Block: "Falsche Liebe"    |###|  rtmpt://cp125301.edgefcs.net/ondemand/mp4:zdf/13/03/130321_bella_block_liebe_neo_1596k_p13v9.mp4

history.txt
----------
Zeile Nr. - 123494
24.11.2016 |#| Serien                    |#| Bella Block - Falsche Liebe               |###|  https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161120_falsche_liebe_bel/1/161120_falsche_liebe_bel_2328k_p35v13.mp4
<-- Obiger Eintrag resultierte soeben. --> 
Zeile Nr. - 123425
24.11.2016 |#| Serien                    |#| Bella Block - Falsche Liebe               |###|  https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161120_falsche_liebe_bel/1/161120_falsche_liebe_bel_2328k_p35v13.mp4
Zeile Nr. - 58224
27.05.2015 |#| Bella Block               |#| Falsche Liebe                             |###|  http://nrodl.zdf.de/none/zdf/15/05/150525_falsche_liebe_ps_bel_2256k_p14v11.mp4
Zeile Nr. - 58159
26.05.2015 |#| Bella Block               |#| Falsche Liebe                             |###|  http://nrodl.zdf.de/none/zdf/15/05/150525_falsche_liebe_ps_bel_2256k_p14v11.mp4
```

Im untenstehendem Bild sind die Attributen dieses DLs zu sehen.  Da mir eine HD-Version lieber wäre, habe ich der URL des Abo-Hits manuell geändert, bevor ich den aus einem Abo-Hit resultierenden DL startete.  Die Änderung -- Download editieren --> Url _(modifizieren}_ -- tut das Gleiche wie die Änderung in https://github.com/mediathekview/MSearch/issues/67 und https://github.com/mediathekview/MSearch/issues/61 beschrieben ist.  

Wenn ich sowieso dabei bin, tue ich immer die gleiche Änderung in der Datei-Name einfügen, damit ich schnell erkennen kann, wie die Datei zustande kam.  Also ersetzte ich "`2328k_p35v13`" mit "`3328k_p36v13`" vom Set Default `ZDF %t (%3%2%1) - %T %N (576pw, 720p, ZDF).mp4`. Nachdem https://github.com/mediathekview/MSearch/issues/67 im Betrieb ist, wird die Datei auch so benannt.

![bella_block_sendung](https://cloud.githubusercontent.com/assets/23268595/20613738/ebef2be2-b294-11e6-865a-fa0618daade1.PNG)

**_Randbemerkung_**. So schaut das Abo aus:

```
<Abonnement>
    <aktiv>true</aktiv>
    <Name>ZDF-BellaBlock</Name>
    <Sender>ZDF</Sender>
    <Irgendwo>Bella Block</Irgendwo>
    <Mindestdauer>12</Mindestdauer>
    <min_max>true</min_max>
    <Zielpfad>ZDF</Zielpfad>
    <letztes_Abo>24.11.2016</letztes_Abo>
    <Programmset>ZDF</Programmset>
</Abonnement>
```

**Comment by zxsd** [comment]
> Eingestellt ist das Abo auf HD.
Wirklich?

**Comment by zxsd** [comment]
BTW. Die Themen dieser "Bella Block" Sendung (in beiden History-Dateien) deuten an, wie schwer es sein könnte, die gewünschten Sendungen als Abo-Hits (im DL-Reiter) zu kriegen.  Über den Jahren habe ich dieses Abo bestimmt ein- oder zweimal editiert. (Vgl. https://github.com/mediathekview/MSearch/issues/62 ...)

**Comment by Nicklas2751** [comment]
> Wirklich?

Ja, das Abo hat das eingestellte Programmset "Speichern" im Programmset ist folgendes hinterlegt:
`<Aufloesung>hd</Aufloesung>`

**Comment by xaverW** [comment]
> Ich denke also es ist doch kein MSearch/Crwaler bug sondern eher nen MView fehler. Oder?

weder noch, es sind unterschiedliche URLs und damit werden auch mehrere Downloads angelegt. In der Datei landet immer die "normale" Auflösung, egal ob HD fürs Abo eingestellt ist und mit der "normalen" Auflösung wird auch in der downloadAbos.txt geschaut, ob schon vorhanden.

Das Problem kommt durch die Umstellung des ZDF und die dadurch unterschiedlichen Auflösungen in der Filmliste.

**Comment by Nicklas2751** [comment]
Aber ein Abo sollte doch erkennen dass die Sendung schon geladen wurde für die eingestellte Qualität oder nicht?

**Comment by xaverW** [comment]
ja, aber wenn sich die URL ändert, ist es ein "neuer" Film für das Abo
(es gibt keinen 100% zuverlässigen Weg, das zu tun da sich auch die Titel und bei Wiederholungen auch das Datum ändern kann, da hat sich die URL als am zuverlässigsten erwiesen)

**Comment by Nicklas2751** [comment]
Können wir dann nicht die URL überprüfen aber halt den Teil mit der Auflösung aus derÜberprüfung rauslassen bzw man könnte gucken ob die Qualität Qualität besser ist und nur wenn ja es nochmal laden.

**Comment by criztovyl** [comment]
Heh, #72 würde in dem Fall vllt auch helfen ^^

**Comment by zxsd** [comment]
> könnte gucken ob die Qualität Qualität besser ist und nur wenn ja es nochmal laden.

Ohne die Sendung im DL-Reiter mittels Abo erscheint, ist jetzt eine derartige Kontrolle äußerst schwer (wenn nicht schier unmöglich) zu unternehmen.  Ich habe erlebt, daß ZDF-Sendungen immer wieder in verbesserter Qualität veröffentlicht werden.  Ich bin aber nur darauf Aufmerksam geworden, weil die Sendung als "neu" von einem Abo identifiziert worden war.

Über den Jahren wurden die gleiche Sendungen mehrmals, mit verschiedenen Qualitätsmerkmalen (erkennbar im Dateinamen), der Reihe nach vom ZDF erneut publiziert: `vh` (als flv und mp4 Datei und fast immer `1586k` aus heutiger Sicht), `1596k`, `2256k` und jetzt` 2328k`. Die Qualitätsmerkmale der damals geltenden "hoch" MV-Version wurde als solchen in den History-Dateien mitprotokolliert.  (_Randbemerkung_. Ich glaube neu benannte Dateien, aus einem neuen Encodierungsdurchlauf seitens ZDF resultieren.)

Für MV-Anwender, die Sendungen zu archivieren pflegen, ist das jetzige Verhalten ein (erwarteter) Bonus. Gerade deswegen kann (mittels Abo) die jüngst veröffentlichte Version mit der archivierten Version der Sendung verglichen werden; wie diese Art von Sendung sonst identifizieren? (Ich habe archivierte Sendungen schon auf diesem Wege aufgebessert, vielleicht mehrmals.  Und ich freue mich wenn ich eine flv-Sendung aus meinem bescheidenen Archiv löschen kann, da ich diese mit einer etwa gleichwertigen mp4-Sendung ersetzen konnte. )

> wenn sich die URL ändert, ist es ein "neuer" Film für das Abo

Und wenn dank einem Abo dieser "neuer Film" im DL-Reiter landet, bin ich immer froh ... sogar jetzt, wenn das Abarbeiten von den vielen ZDF-Abo-Hits viel Zeit kostet.  In einigen Wochen wird (hoffentlich) der tägliche Sturm von neuen Sendungen nur eine schlechte Erinnerung sein.

**Comment by Nicklas2751** [comment]
Dann sollte man das ganze doch als option in den Einstellungen anbieten. Bei den Abbo Optionen sowas wie: "Neue Folge nur einmal herunterladen" und dann ein entsprechender Hilfetext: "Eine neue Folge dieses Abos wird nur ein einziges mal mit der ausgewählten, oder der ausgewählten am nahekommensten, Qualität heruntergeladen. Wird später eine Version mit besserer Qualität gefunden wird diese nicht erneut heruntergeladen".

**Comment by xaverW** [comment]
> Können wir dann nicht die URL überprüfen aber halt den Teil mit der Auflösung aus derÜberprüfung rauslassen bzw man könnte gucken ob die Qualität Qualität besser ist und nur wenn ja es nochmal laden.

> Heh, #72 würde in dem Fall vllt auch helfen ^^

1. geht nicht zuverlässig, da sich das Merkmal mit der Auflösung nicht zuverlässig auslesen lässt und weil sich auch andere Teile einer URL ändern
2. geht nicht, da sich auch der Titel manchmal ändert.

--> Das Problem gibt es seit es Abos gibt und ich habe bis jetzt keine zuverlässige Möglichkeit gefunden, Sendungen 100% zu identifizieren. URL ist das was sich am besten herausgestellt hat (ZDF ist jetzt ein Problem wegen der Umstellungen des Senders, eine Möglichkeit wäre, aus den alten Listen die alten Sendungen des ZDF zu löschen, dann wäre die weg)
