### ISSUE TITLE
Enhancement: Liste der Filmliste-servierenden Server aktualisieren lassen ...

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MLib#73]
... entweder automatisch (zentral-gesteuert ... beispielsweise nachdem der jeweiligen Server dermaßen eingestellt worden war) oder infolge Benutzerinteraktion.  Letztere könnte eventuell so ausschauen:

![enhancement-filmliste-servierende-server-liste-aktualisieren](https://cloud.githubusercontent.com/assets/23268595/20640302/c565e966-b3a7-11e6-8aed-93aaa5f28e54.png)

[Die traurige Geschichte](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2272), bzw. der Hintergrund dieses Issues, ist in MV-Help-Forum zu lesen.  Als ich dieses poste, fehlt eine Rückmeldung vom MV-Thread-Autor, **fra-wa**, zum vierten Beitrag (von mir).

**Comment by bagbag** [comment]
@alex1702 @Nicklas2751 
Das hat sich ja jetzt mit http://liste.mediathekview.de/ erledigt?

**Comment by alex1702** [comment]
> @alex1702 @Nicklas2751
> Das hat sich ja jetzt mit https://liste.mediathekview.de/ erledigt?

Jap
